name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    - name: Dynamically set MY_DATE environment variable
      run: echo "DATE=$(date +%s)" >> $GITHUB_ENV
    - name: Test DATE variable
      run: echo ${{ env.DATE }}

    - name: Docker login
      run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" docker.io

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag adriel/streamlink-autodl

    - name: Look up images
      run: docker image ls
      run: docker images

    - name: Docker Push
      run: docker push adriel/streamlink-autodl
