name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set current date as env variable
      run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo $NOW

      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}


    - name: Docker login
      run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag adriel/streamlink-autodl:$DATE

    - name: Look up images
      run: docker image ls

    - name: Docker Push
      run: docker push adriel/streamlink-autodl:$DATE
