name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    - name: docker login
      run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag adriel/streamlink-autodl:$(date +%s)

    - name: Docker Push
      run: docker push adriel/streamlink-autodl:$(date +%s)
